<?php

namespace AB\AdBoardBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository {

    public function myFind($string, $limit) {
        return $this->getEntityManager()->createQuery('SELECT a FROM ABAdBoardBundle:Advert a  
            WHERE a.title LIKE :string ')
                        ->setParameter('string', '%' . $string . '%')
                        ->setMaxResults($limit)
                        ->getResult();
    }
    
    public function lastTen(){
        
        return $this->getEntityManager()->createQuery('SELECT a FROM ABAdBoardBundle:Advert a ORDER BY a.creationTime')
                ->setMaxResults(10)
                ->getResult();
        
    }

}
